### ISSUE TITLE
Can i use request & response classes without composer? 

### ISSUE THREAD

**Issue by Shilpafinesoft** [BitGo/express-php-sdk#1]

**Comment by arik-so** [comment]
Hi, are you referring to our Unirest dependency for HTTP request and response handling? If so, I can refer you to their website, http://unirest.io/php.html, where they have installation instructions for both with and without composer.

**Comment by Shilpafinesoft** [comment]
I Have used the unirest dependencies , but i am getting exception while setting address label. Can yo please tell me a way out for that.   when i am using handleresponse() i am getting response code as 405 which is an error. Please tell me how can i resolve that asap, or can i set address label using the curl method ???? if yes, then please tell me the solution for that

**Comment by arik-so** [comment]
Hi, might I ask you to provide a code snippet? That would be most helpful.

**Comment by Shilpafinesoft** [comment]
yes ofcourse ,

I am using this function to create wallet address from wallet id first & then setting address label from the same function calling another function from different class.

function createnewaddress()
{

require('BitGoSDK.php');
$sdk = new BitGoSDK();
$sdk->login(BITGOEMAILID, BITGOPASSWORD, '0000000');
$walletid=$sdk->listWallets();
**$address=$sdk->createwalletaddress($walletid);**
$redeemScript=$address['redeemScript'];
$walletaddress=$address['address'];
$label="Any Address Label";
**$addresslabel=$sdk->setAddressLabel($walletaddress, $label,$walletid);**
var_dump($addresslabel);
exit;
}

for creating address i am using the below mentioned function & it is working perfect,

function createwalletaddress($WALLETID) {
         $CHAIN=0;
  $curl = curl_init(self::BITGO_EXPRESS_ENDPOINT'/wallet/'.urlencode($WALLETID).'/address/'.urlencode($CHAIN));
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($curl, CURLOPT_HTTPHEADER, array(
            'Content-Type: application/json',
            'Authorization: Bearer ' . $this->accessToken
        ));
        curl_setopt($curl, CURLOPT_POST, true);
        curl_setopt($curl, CURLOPT_POSTFIELDS, json_encode(
           array (
               'walletid' => $this->walletid,
                'chain' => '0'
            )
        ));
        $responseString = curl_exec($curl);
        curl_close($curl);

        $response = json_decode($responseString, true);
       return $response;
    }
 
and for setting address label i am using the same method which is given in your example file, Can you please suggest me a a function for setting address label in the form of curl methods,that would be a great help

**Comment by masonicGIT** [comment]
Closing since its not referring to a problem/issue with the package :-)

-Mason
